import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import coffeeIcon from "../public/static/day79-coffee.svg";
import Banner from "@/components/banner";
import Card from "@/components/card";

import coffeeStores from "../data/coffee-stores.json";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Banner buttonText="View stores nearby" />
        <div className={styles.heroImage}>
          <Image src={coffeeIcon} alt="hero" width={500} height={500} />
        </div>
        <div className={styles.cardLayout}>
          {coffeeStores.map((store) => {
            return (
              <Card
                key={store.id}
                name={store.name}
                imgUrl={store.imgUrl}
                href={`/coffee-store/${store.id}`}
                className={styles.card}
              />
            );
          })}
        </div>
      </main>
    </>
  );
}
